
//tts_cnfg_2 output date: 1/18/2017 8:44:27 PM

#define	TTS_ADDR_ZERO_INDEX	1L
#define	TTS_ADDR_ONE_INDEX	2L
#define	TTS_ADDR_TWO_INDEX	3L
#define	TTS_ADDR_THREE_INDEX	4L
#define	TTS_ADDR_FOUR_INDEX	5L
#define	TTS_ADDR_FIVE_INDEX	6L
#define	TTS_ADDR_SIX_INDEX	7L
#define	TTS_ADDR_SEVEN_INDEX	8L
#define	TTS_ADDR_EIGHT_INDEX	9L
#define	TTS_ADDR_NINE_INDEX	10L
#define	TTS_ADDR_TEN_INDEX	11L
#define	TTS_ADDR_ELEVEN_INDEX	12L
#define	TTS_ADDR_TWELVE_INDEX	13L
#define	TTS_ADDR_THIRTEEN_INDEX	14L
#define	TTS_ADDR_FOURTEEN_INDEX	15L
#define	TTS_ADDR_FIFTEEN_INDEX	16L
#define	TTS_ADDR_SIXTEEN_INDEX	17L
#define	TTS_ADDR_SEVENTEEN_INDEX	18L
#define	TTS_ADDR_EIGHTEEN_INDEX	19L
#define	TTS_ADDR_NINETEEN_INDEX	20L
#define	TTS_ADDR_TWENTY_INDEX	21L
#define	TTS_ADDR_THIRTY_INDEX	22L
#define	TTS_ADDR_FORTY_INDEX	23L
#define	TTS_ADDR_FIFTY_INDEX	24L
#define	TTS_ADDR_SIXTY_INDEX	25L
#define	TTS_ADDR_SEVENTY_INDEX	26L
#define	TTS_ADDR_EIGHTY_INDEX	27L
#define	TTS_ADDR_NINETY_INDEX	28L
#define	TTS_ADDR_1HUNDRED_INDEX	29L
#define	TTS_ADDR_2HUNDRED_INDEX	30L
#define	TTS_ADDR_3HUNDRED_INDEX	31L
#define	TTS_ADDR_4HUNDRED_INDEX	32L
#define	TTS_ADDR_5HUNDRED_INDEX	33L
#define	TTS_ADDR_6HUNDRED_INDEX	34L
#define	TTS_ADDR_7HUNDRED_INDEX	35L
#define	TTS_ADDR_8HUNDRED_INDEX	36L
#define	TTS_ADDR_9HUNDRED_INDEX	37L
#define	TTS_ADDR_THOUSAND_INDEX	38L
#define	TTS_ADDR_4800_MID_INDEX	39L
#define	TTS_ADDR_4800_END_INDEX	40L
#define	TTS_ADDR_9600_MID_INDEX	41L
#define	TTS_ADDR_9600_END_INDEX	42L
#define	TTS_ADDR_19_2K_MID_INDEX	43L
#define	TTS_ADDR_19_2K_END_INDEX	44L
#define	TTS_ADDR_38_4K_MID_INDEX	45L
#define	TTS_ADDR_38_4K_END_INDEX	46L
#define	TTS_ADDR_A2B_MID_INDEX	47L
#define	TTS_ADDR_ADSC_INDEX	48L
#define	TTS_ADDR_AUDIO_COMPASS_MID_INDEX	49L
#define	TTS_ADDR_AUDIO_COMPASS_END_INDEX	50L
#define	TTS_ADDR_AUD_CPS_OPTS_MID_INDEX	51L
#define	TTS_ADDR_AUD_CPS_OPTS_END_INDEX	52L
#define	TTS_ADDR_AUTOMATIC_MID_INDEX	53L
#define	TTS_ADDR_AUTOMATIC_END_INDEX	54L
#define	TTS_ADDR_B2A_MID_INDEX	55L
#define	TTS_ADDR_BTW_MID_INDEX	56L
#define	TTS_ADDR_BTW_END_INDEX	57L
#define	TTS_ADDR_CNFG_SAVED_INDEX	58L
#define	TTS_ADDR_COMPASS_HDG_MID_INDEX	59L
#define	TTS_ADDR_COMPASS_HDG_END_INDEX	60L
#define	TTS_ADDR_COMPASS_HDM_MID_INDEX	61L
#define	TTS_ADDR_COMPASS_HDM_END_INDEX	62L
#define	TTS_ADDR_COMPASS_MID_INDEX	63L
#define	TTS_ADDR_COMPASS_END_INDEX	64L
#define	TTS_ADDR_CONFIG_INDEX	65L
#define	TTS_ADDR_DECREASE_INDEX	66L
#define	TTS_ADDR_DEGREES_MID_INDEX	67L
#define	TTS_ADDR_DEGREES_END_INDEX	68L
#define	TTS_ADDR_DELTA_INTERVAL_MID_INDEX	69L
#define	TTS_ADDR_DELTA_SIGNAL_MID_INDEX	70L
#define	TTS_ADDR_DIGIT_INDEX	71L
#define	TTS_ADDR_DISPLAY_INDEX	72L
#define	TTS_ADDR_DTW_MID_INDEX	73L
#define	TTS_ADDR_DTW_END_INDEX	74L
#define	TTS_ADDR_ERROR_INDEX	75L
#define	TTS_ADDR_EXT_MID_INDEX	76L
#define	TTS_ADDR_FMT_INDEX	77L
#define	TTS_ADDR_FMT_OPTS_MID_INDEX	78L
#define	TTS_ADDR_FMT_OPTS_END_INDEX	79L
#define	TTS_ADDR_FREQ_INDEX	80L
#define	TTS_ADDR_GPS_MID_INDEX	81L
#define	TTS_ADDR_GPS_END_INDEX	82L
#define	TTS_ADDR_GPS_MOD_INDEX	83L
#define	TTS_ADDR_GPS_OPTS_MID_INDEX	84L
#define	TTS_ADDR_GPS_OPTS_END_INDEX	85L
#define	TTS_ADDR_HDG_MID_INDEX	86L
#define	TTS_ADDR_HDG_END_INDEX	87L
#define	TTS_ADDR_HIGH_MID_INDEX	88L
#define	TTS_ADDR_HIGH_END_INDEX	89L
#define	TTS_ADDR_INCREASE_INDEX	90L
#define	TTS_ADDR_INITIALIZING_INDEX	91L
#define	TTS_ADDR_KNOTS_END_INDEX	92L
#define	TTS_ADDR_LEFT_INDEX	93L
#define	TTS_ADDR_LEVEL_INDEX	94L
#define	TTS_ADDR_LOOP_INDEX	95L
#define	TTS_ADDR_LOW_MID_INDEX	96L
#define	TTS_ADDR_LOW_END_INDEX	97L
#define	TTS_ADDR_MAGNETIC_MID_INDEX	98L
#define	TTS_ADDR_MAGNETIC_END_INDEX	99L
#define	TTS_ADDR_MAIN_INDEX	100L
#define	TTS_ADDR_MAIN_MENU_INDEX	101L
#define	TTS_ADDR_MAX_PERIOD_MID_INDEX	102L
#define	TTS_ADDR_MEDIUM_MID_INDEX	103L
#define	TTS_ADDR_MEDIUM_END_INDEX	104L
#define	TTS_ADDR_MENU_INDEX	105L
#define	TTS_ADDR_MESSAGE_INDEX	106L
#define	TTS_ADDR_MINUS_INDEX	107L
#define	TTS_ADDR_MIN_PERIOD_MID_INDEX	108L
#define	TTS_ADDR_MODE_INDEX	109L
#define	TTS_ADDR_MUTE_INDEX	110L
#define	TTS_ADDR_MUTED_INDEX	111L
#define	TTS_ADDR_NAUTICALMILES_INDEX	112L
#define	TTS_ADDR_NAVIGATION_INDEX	113L
#define	TTS_ADDR_NEARING_INDEX	114L
#define	TTS_ADDR_NO_SIGNAL_INDEX	115L
#define	TTS_ADDR_NONTARGETING_INDEX	116L
#define	TTS_ADDR_NOTRCVING_INDEX	117L
#define	TTS_ADDR_OFF_MID_INDEX	118L
#define	TTS_ADDR_OFF_END_INDEX	119L
#define	TTS_ADDR_ON_MID_INDEX	120L
#define	TTS_ADDR_ON_END_INDEX	121L
#define	TTS_ADDR_ONCOURSE_INDEX	122L
#define	TTS_ADDR_OPTIONS_INDEX	123L
#define	TTS_ADDR_PER_RPT_MID_INDEX	124L
#define	TTS_ADDR_PER_RPT_END_INDEX	125L
#define	TTS_ADDR_POINT_INDEX	126L
#define	TTS_ADDR_PORT_INDEX	127L
#define	TTS_ADDR_PORTA_INDEX	128L
#define	TTS_ADDR_PORTA2B_INDEX	129L
#define	TTS_ADDR_PORTB2A_INDEX	130L
#define	TTS_ADDR_PORTB_INDEX	131L
#define	TTS_ADDR_PRESENT_INDEX	132L
#define	TTS_ADDR_RCVING_INDEX	133L
#define	TTS_ADDR_READY_INDEX	134L
#define	TTS_ADDR_REPORT_INDEX	135L
#define	TTS_ADDR_RESOLUTION_INDEX	136L
#define	TTS_ADDR_RIGHT_INDEX	137L
#define	TTS_ADDR_SECONDS_MID_INDEX	138L
#define	TTS_ADDR_SECONDS_END_INDEX	139L
#define	TTS_ADDR_SELECTED_INDEX	140L
#define	TTS_ADDR_SIGNAL_INDEX	141L
#define	TTS_ADDR_SOURCE_INDEX	142L
#define	TTS_ADDR_SPACE_INDEX	143L
#define	TTS_ADDR_SPEECH_INDEX	144L
#define	TTS_ADDR_SPEED_MID_INDEX	145L
#define	TTS_ADDR_STATUS_BTN_OPTS_MID_INDEX	146L
#define	TTS_ADDR_STATUS_BTN_OPTS_END_INDEX	147L
#define	TTS_ADDR_STARBOARD_INDEX	148L
#define	TTS_ADDR_ADJUST_MID_INDEX	149L
#define	TTS_ADDR_SWITCH_INDEX	150L
#define	TTS_ADDR_SWITCHING_INDEX	151L
#define	TTS_ADDR_SWITCHING_OPTS_MID_INDEX	152L
#define	TTS_ADDR_SWITCHING_OPTS_END_INDEX	153L
#define	TTS_ADDR_SYSTEM_INDEX	154L
#define	TTS_ADDR_SYSTEM_OPTS_MID_INDEX	155L
#define	TTS_ADDR_SYSTEM_OPTS_END_INDEX	156L
#define	TTS_ADDR_SYSTEM_RPT_INDEX	157L
#define	TTS_ADDR_TARGET_INDEX	158L
#define	TTS_ADDR_TARGETING_INDEX	159L
#define	TTS_ADDR_TONE_INDEX	160L
#define	TTS_ADDR_TRUE_MID_INDEX	161L
#define	TTS_ADDR_TRUE_END_INDEX	162L
#define	TTS_ADDR_TURNTO_INDEX	163L
#define	TTS_ADDR_USE_MID_INDEX	164L
#define	TTS_ADDR_USING_INDEX	165L
#define	TTS_ADDR_VELOCITY_INDEX	166L
#define	TTS_ADDR_VTW_INDEX	167L
#define	TTS_ADDR_VERSION_INDEX	168L
#define	TTS_ADDR_VOG_MID_INDEX	169L
#define	TTS_ADDR_VOG_END_INDEX	170L
#define	TTS_ADDR_VOLUME_INDEX	171L
#define	TTS_ADDR_WPT_MID_INDEX	172L
#define	TTS_ADDR_WPT_END_INDEX	173L
#define	TTS_ADDR_WIND_INDEX	174L
#define	TTS_ADDR_XTRACKERR_INDEX	175L
#define	TTS_ADDR_A_INDEX	176L
#define	TTS_ADDR_B_INDEX	177L
#define	TTS_ADDR_C_INDEX	178L
#define	TTS_ADDR_D_INDEX	179L
#define	TTS_ADDR_E_INDEX	180L
#define	TTS_ADDR_F_INDEX	181L
#define	TTS_ADDR_G_INDEX	182L
#define	TTS_ADDR_H_INDEX	183L
#define	TTS_ADDR_I_INDEX	184L
#define	TTS_ADDR_J_INDEX	185L
#define	TTS_ADDR_K_INDEX	186L
#define	TTS_ADDR_L_INDEX	187L
#define	TTS_ADDR_M_INDEX	188L
#define	TTS_ADDR_N_INDEX	189L
#define	TTS_ADDR_O_INDEX	190L
#define	TTS_ADDR_P_INDEX	191L
#define	TTS_ADDR_Q_INDEX	192L
#define	TTS_ADDR_R_INDEX	193L
#define	TTS_ADDR_S_INDEX	194L
#define	TTS_ADDR_T_INDEX	195L
#define	TTS_ADDR_U_INDEX	196L
#define	TTS_ADDR_V_INDEX	197L
#define	TTS_ADDR_W_INDEX	198L
#define	TTS_ADDR_X_INDEX	199L
#define	TTS_ADDR_Y_INDEX	200L
#define	TTS_ADDR_Z_INDEX	201L
#define	TTS_ADDR_NOTE_C4_INDEX	202L
#define	TTS_ADDR_NOTE_DF4_INDEX	203L
#define	TTS_ADDR_NOTE_D4_INDEX	204L
#define	TTS_ADDR_NOTE_EF4_INDEX	205L
#define	TTS_ADDR_NOTE_E4_INDEX	206L
#define	TTS_ADDR_NOTE_F4_INDEX	207L
#define	TTS_ADDR_NOTE_GF4_INDEX	208L
#define	TTS_ADDR_NOTE_G4_INDEX	209L
#define	TTS_ADDR_NOTE_AF4_INDEX	210L
#define	TTS_ADDR_NOTE_A4_INDEX	211L
#define	TTS_ADDR_NOTE_BF4_INDEX	212L
#define	TTS_ADDR_NOTE_B4_INDEX	213L
#define	TTS_ADDR_NOTE_DBL_E4_INDEX	214L
#define	TTS_ADDR_NOTE_E4_2_INDEX	215L
#define	TTS_ADDR_NOTE_A4_B4_INDEX	216L
#define	TTS_ADDR_NOTE_B4_A4_INDEX	217L
#define	TTS_ADDR_NOTE_A4_F4_INDEX	218L
#define	TTS_ADDR_NOTE_F4_A4_INDEX	219L
#define	TTS_ADDR_NOTE_C4_E4_INDEX	220L
#define	TTS_ADDR_NOTE_E4_C4_INDEX	221L
#define	TTS_ADDR_NOTE_D4_F4_INDEX	222L
#define	TTS_ADDR_NOTE_F4_D4_INDEX	223L
#define	TTS_ADDR_NOTE_E4_G4_INDEX	224L
#define	TTS_ADDR_NOTE_G4_E4_INDEX	225L
#define	TTS_ADDR_NOTE_C5_INDEX	226L
#define	TTS_ADDR_NOTE_DF5_INDEX	227L
#define	TTS_ADDR_NOTE_D5_INDEX	228L
#define	TTS_ADDR_NOTE_EF5_INDEX	229L
#define	TTS_ADDR_NOTE_E5_INDEX	230L
#define	TTS_ADDR_NOTE_GF5_INDEX	231L
#define	TTS_ADDR_NOTE_G5_INDEX	232L
#define	TTS_ADDR_TURN_TO_PORT_INDEX	233L
#define	TTS_ADDR_TURN_TO_STBD_INDEX	234L
#define	TTS_ADDR_HEADING_STEADY_INDEX	235L
#define	TTS_ADDR_DELTA_STBD_INDEX	236L
#define	TTS_ADDR_DELTA_PORT_INDEX	237L

#define	TTS_ADDR_MAX_INDEX	237

#define	TTS_ADDR_ZERO	0
#define	TTS_ADDR_ONE	4
#define	TTS_ADDR_TWO	7
#define	TTS_ADDR_THREE	10
#define	TTS_ADDR_FOUR	14
#define	TTS_ADDR_FIVE	18
#define	TTS_ADDR_SIX	22
#define	TTS_ADDR_SEVEN	26
#define	TTS_ADDR_EIGHT	30
#define	TTS_ADDR_NINE	34
#define	TTS_ADDR_TEN	38
#define	TTS_ADDR_ELEVEN	42
#define	TTS_ADDR_TWELVE	46
#define	TTS_ADDR_THIRTEEN	50
#define	TTS_ADDR_FOURTEEN	55
#define	TTS_ADDR_FIFTEEN	59
#define	TTS_ADDR_SIXTEEN	63
#define	TTS_ADDR_SEVENTEEN	68
#define	TTS_ADDR_EIGHTEEN	73
#define	TTS_ADDR_NINETEEN	77
#define	TTS_ADDR_TWENTY	82
#define	TTS_ADDR_THIRTY	86
#define	TTS_ADDR_FORTY	90
#define	TTS_ADDR_FIFTY	94
#define	TTS_ADDR_SIXTY	98
#define	TTS_ADDR_SEVENTY	102
#define	TTS_ADDR_EIGHTY	106
#define	TTS_ADDR_NINETY	109
#define	TTS_ADDR_1HUNDRED	112
#define	TTS_ADDR_2HUNDRED	117
#define	TTS_ADDR_3HUNDRED	122
#define	TTS_ADDR_4HUNDRED	127
#define	TTS_ADDR_5HUNDRED	131
#define	TTS_ADDR_6HUNDRED	136
#define	TTS_ADDR_7HUNDRED	141
#define	TTS_ADDR_8HUNDRED	147
#define	TTS_ADDR_9HUNDRED	151
#define	TTS_ADDR_THOUSAND	156
#define	TTS_ADDR_4800_MID	161
#define	TTS_ADDR_4800_END	168
#define	TTS_ADDR_9600_MID	175
#define	TTS_ADDR_9600_END	182
#define	TTS_ADDR_19_2K_MID	189
#define	TTS_ADDR_19_2K_END	198
#define	TTS_ADDR_38_4K_MID	208
#define	TTS_ADDR_38_4K_END	216
#define	TTS_ADDR_A2B_MID	225
#define	TTS_ADDR_ADSC	230
#define	TTS_ADDR_AUDIO_COMPASS_MID	240
#define	TTS_ADDR_AUDIO_COMPASS_END	247
#define	TTS_ADDR_AUD_CPS_OPTS_MID	254
#define	TTS_ADDR_AUD_CPS_OPTS_END	263
#define	TTS_ADDR_AUTOMATIC_MID	272
#define	TTS_ADDR_AUTOMATIC_END	276
#define	TTS_ADDR_B2A_MID	281
#define	TTS_ADDR_BTW_MID	285
#define	TTS_ADDR_BTW_END	292
#define	TTS_ADDR_CNFG_SAVED	300
#define	TTS_ADDR_COMPASS_HDG_MID	309
#define	TTS_ADDR_COMPASS_HDG_END	319
#define	TTS_ADDR_COMPASS_HDM_MID	328
#define	TTS_ADDR_COMPASS_HDM_END	337
#define	TTS_ADDR_COMPASS_MID	346
#define	TTS_ADDR_COMPASS_END	350
#define	TTS_ADDR_CONFIG	355
#define	TTS_ADDR_DECREASE	360
#define	TTS_ADDR_DEGREES_MID	366
#define	TTS_ADDR_DEGREES_END	370
#define	TTS_ADDR_DELTA_INTERVAL_MID	375
#define	TTS_ADDR_DELTA_SIGNAL_MID	382
#define	TTS_ADDR_DIGIT	391
#define	TTS_ADDR_DISPLAY	395
#define	TTS_ADDR_DTW_MID	401
#define	TTS_ADDR_DTW_END	409
#define	TTS_ADDR_ERROR	417
#define	TTS_ADDR_EXT_MID	421
#define	TTS_ADDR_FMT	426
#define	TTS_ADDR_FMT_OPTS_MID	434
#define	TTS_ADDR_FMT_OPTS_END	444
#define	TTS_ADDR_FREQ	455
#define	TTS_ADDR_GPS_MID	461
#define	TTS_ADDR_GPS_END	467
#define	TTS_ADDR_GPS_MOD	474
#define	TTS_ADDR_GPS_OPTS_MID	481
#define	TTS_ADDR_GPS_OPTS_END	491
#define	TTS_ADDR_HDG_MID	501
#define	TTS_ADDR_HDG_END	505
#define	TTS_ADDR_HIGH_MID	509
#define	TTS_ADDR_HIGH_END	513
#define	TTS_ADDR_INCREASE	517
#define	TTS_ADDR_INITIALIZING	522
#define	TTS_ADDR_KNOTS_END	528
#define	TTS_ADDR_LEFT	533
#define	TTS_ADDR_LEVEL	537
#define	TTS_ADDR_LOOP	541
#define	TTS_ADDR_LOW_MID	544
#define	TTS_ADDR_LOW_END	548
#define	TTS_ADDR_MAGNETIC_MID	552
#define	TTS_ADDR_MAGNETIC_END	557
#define	TTS_ADDR_MAIN	562
#define	TTS_ADDR_MAIN_MENU	566
#define	TTS_ADDR_MAX_PERIOD_MID	571
#define	TTS_ADDR_MEDIUM_MID	577
#define	TTS_ADDR_MEDIUM_END	581
#define	TTS_ADDR_MENU	586
#define	TTS_ADDR_MESSAGE	591
#define	TTS_ADDR_MINUS	596
#define	TTS_ADDR_MIN_PERIOD_MID	601
#define	TTS_ADDR_MODE	607
#define	TTS_ADDR_MUTE	611
#define	TTS_ADDR_MUTED	615
#define	TTS_ADDR_NAUTICALMILES	619
#define	TTS_ADDR_NAVIGATION	626
#define	TTS_ADDR_NEARING	632
#define	TTS_ADDR_NO_SIGNAL	636
#define	TTS_ADDR_NONTARGETING	641
#define	TTS_ADDR_NOTRCVING	648
#define	TTS_ADDR_OFF_MID	654
#define	TTS_ADDR_OFF_END	657
#define	TTS_ADDR_ON_MID	661
#define	TTS_ADDR_ON_END	664
#define	TTS_ADDR_ONCOURSE	668
#define	TTS_ADDR_OPTIONS	674
#define	TTS_ADDR_PER_RPT_MID	679
#define	TTS_ADDR_PER_RPT_END	686
#define	TTS_ADDR_POINT	693
#define	TTS_ADDR_PORT	696
#define	TTS_ADDR_PORTA	699
#define	TTS_ADDR_PORTA2B	705
#define	TTS_ADDR_PORTB2A	711
#define	TTS_ADDR_PORTB	717
#define	TTS_ADDR_PRESENT	723
#define	TTS_ADDR_RCVING	727
#define	TTS_ADDR_READY	732
#define	TTS_ADDR_REPORT	736
#define	TTS_ADDR_RESOLUTION	740
#define	TTS_ADDR_RIGHT	746
#define	TTS_ADDR_SECONDS_MID	750
#define	TTS_ADDR_SECONDS_END	754
#define	TTS_ADDR_SELECTED	759
#define	TTS_ADDR_SIGNAL	764
#define	TTS_ADDR_SOURCE	769
#define	TTS_ADDR_SPACE	774
#define	TTS_ADDR_SPEECH	780
#define	TTS_ADDR_SPEED_MID	784
#define	TTS_ADDR_STATUS_BTN_OPTS_MID	788
#define	TTS_ADDR_STATUS_BTN_OPTS_END	797
#define	TTS_ADDR_STARBOARD	806
#define	TTS_ADDR_ADJUST_MID	812
#define	TTS_ADDR_SWITCH	816
#define	TTS_ADDR_SWITCHING	821
#define	TTS_ADDR_SWITCHING_OPTS_MID	826
#define	TTS_ADDR_SWITCHING_OPTS_END	834
#define	TTS_ADDR_SYSTEM	842
#define	TTS_ADDR_SYSTEM_OPTS_MID	847
#define	TTS_ADDR_SYSTEM_OPTS_END	854
#define	TTS_ADDR_SYSTEM_RPT	861
#define	TTS_ADDR_TARGET	867
#define	TTS_ADDR_TARGETING	871
#define	TTS_ADDR_TONE	876
#define	TTS_ADDR_TRUE_MID	880
#define	TTS_ADDR_TRUE_END	883
#define	TTS_ADDR_TURNTO	887
#define	TTS_ADDR_USE_MID	891
#define	TTS_ADDR_USING	894
#define	TTS_ADDR_VELOCITY	898
#define	TTS_ADDR_VTW	903
#define	TTS_ADDR_VERSION	912
#define	TTS_ADDR_VOG_MID	917
#define	TTS_ADDR_VOG_END	926
#define	TTS_ADDR_VOLUME	935
#define	TTS_ADDR_WPT_MID	940
#define	TTS_ADDR_WPT_END	945
#define	TTS_ADDR_WIND	950
#define	TTS_ADDR_XTRACKERR	953
#define	TTS_ADDR_A	962
#define	TTS_ADDR_B	966
#define	TTS_ADDR_C	970
#define	TTS_ADDR_D	975
#define	TTS_ADDR_E	979
#define	TTS_ADDR_F	983
#define	TTS_ADDR_G	987
#define	TTS_ADDR_H	991
#define	TTS_ADDR_I	995
#define	TTS_ADDR_J	1000
#define	TTS_ADDR_K	1005
#define	TTS_ADDR_L	1009
#define	TTS_ADDR_M	1013
#define	TTS_ADDR_N	1017
#define	TTS_ADDR_O	1020
#define	TTS_ADDR_P	1024
#define	TTS_ADDR_Q	1028
#define	TTS_ADDR_R	1032
#define	TTS_ADDR_S	1036
#define	TTS_ADDR_T	1040
#define	TTS_ADDR_U	1044
#define	TTS_ADDR_V	1048
#define	TTS_ADDR_W	1052
#define	TTS_ADDR_X	1057
#define	TTS_ADDR_Y	1061
#define	TTS_ADDR_Z	1065
#define	TTS_ADDR_NOTE_C4	1069
#define	TTS_ADDR_NOTE_DF4	1072
#define	TTS_ADDR_NOTE_D4	1075
#define	TTS_ADDR_NOTE_EF4	1078
#define	TTS_ADDR_NOTE_E4	1081
#define	TTS_ADDR_NOTE_F4	1084
#define	TTS_ADDR_NOTE_GF4	1088
#define	TTS_ADDR_NOTE_G4	1091
#define	TTS_ADDR_NOTE_AF4	1094
#define	TTS_ADDR_NOTE_A4	1097
#define	TTS_ADDR_NOTE_BF4	1100
#define	TTS_ADDR_NOTE_B4	1103
#define	TTS_ADDR_NOTE_DBL_E4	1106
#define	TTS_ADDR_NOTE_E4_2	1110
#define	TTS_ADDR_NOTE_A4_B4	1114
#define	TTS_ADDR_NOTE_B4_A4	1118
#define	TTS_ADDR_NOTE_A4_F4	1122
#define	TTS_ADDR_NOTE_F4_A4	1126
#define	TTS_ADDR_NOTE_C4_E4	1130
#define	TTS_ADDR_NOTE_E4_C4	1134
#define	TTS_ADDR_NOTE_D4_F4	1138
#define	TTS_ADDR_NOTE_F4_D4	1142
#define	TTS_ADDR_NOTE_E4_G4	1146
#define	TTS_ADDR_NOTE_G4_E4	1150
#define	TTS_ADDR_NOTE_C5	1154
#define	TTS_ADDR_NOTE_DF5	1157
#define	TTS_ADDR_NOTE_D5	1160
#define	TTS_ADDR_NOTE_EF5	1163
#define	TTS_ADDR_NOTE_E5	1166
#define	TTS_ADDR_NOTE_GF5	1169
#define	TTS_ADDR_NOTE_G5	1172
#define	TTS_ADDR_TURN_TO_PORT	1175
#define	TTS_ADDR_TURN_TO_STBD	1179
#define	TTS_ADDR_HEADING_STEADY	1183
#define	TTS_ADDR_DELTA_STBD	1187
#define	TTS_ADDR_DELTA_PORT	1190

#define	TTS_ADDR_MAX	1190


#ifdef TTS

const int16 TtsAddrSpchTbl[TTS_ADDR_MAX_INDEX+1] = {
0, //Not Used
	TTS_ADDR_ZERO,
	TTS_ADDR_ONE,
	TTS_ADDR_TWO,
	TTS_ADDR_THREE,
	TTS_ADDR_FOUR,
	TTS_ADDR_FIVE,
	TTS_ADDR_SIX,
	TTS_ADDR_SEVEN,
	TTS_ADDR_EIGHT,
	TTS_ADDR_NINE,
	TTS_ADDR_TEN,
	TTS_ADDR_ELEVEN,
	TTS_ADDR_TWELVE,
	TTS_ADDR_THIRTEEN,
	TTS_ADDR_FOURTEEN,
	TTS_ADDR_FIFTEEN,
	TTS_ADDR_SIXTEEN,
	TTS_ADDR_SEVENTEEN,
	TTS_ADDR_EIGHTEEN,
	TTS_ADDR_NINETEEN,
	TTS_ADDR_TWENTY,
	TTS_ADDR_THIRTY,
	TTS_ADDR_FORTY,
	TTS_ADDR_FIFTY,
	TTS_ADDR_SIXTY,
	TTS_ADDR_SEVENTY,
	TTS_ADDR_EIGHTY,
	TTS_ADDR_NINETY,
	TTS_ADDR_1HUNDRED,
	TTS_ADDR_2HUNDRED,
	TTS_ADDR_3HUNDRED,
	TTS_ADDR_4HUNDRED,
	TTS_ADDR_5HUNDRED,
	TTS_ADDR_6HUNDRED,
	TTS_ADDR_7HUNDRED,
	TTS_ADDR_8HUNDRED,
	TTS_ADDR_9HUNDRED,
	TTS_ADDR_THOUSAND,
	TTS_ADDR_4800_MID,
	TTS_ADDR_4800_END,
	TTS_ADDR_9600_MID,
	TTS_ADDR_9600_END,
	TTS_ADDR_19_2K_MID,
	TTS_ADDR_19_2K_END,
	TTS_ADDR_38_4K_MID,
	TTS_ADDR_38_4K_END,
	TTS_ADDR_A2B_MID,
	TTS_ADDR_ADSC,
	TTS_ADDR_AUDIO_COMPASS_MID,
	TTS_ADDR_AUDIO_COMPASS_END,
	TTS_ADDR_AUD_CPS_OPTS_MID,
	TTS_ADDR_AUD_CPS_OPTS_END,
	TTS_ADDR_AUTOMATIC_MID,
	TTS_ADDR_AUTOMATIC_END,
	TTS_ADDR_B2A_MID,
	TTS_ADDR_BTW_MID,
	TTS_ADDR_BTW_END,
	TTS_ADDR_CNFG_SAVED,
	TTS_ADDR_COMPASS_HDG_MID,
	TTS_ADDR_COMPASS_HDG_END,
	TTS_ADDR_COMPASS_HDM_MID,
	TTS_ADDR_COMPASS_HDM_END,
	TTS_ADDR_COMPASS_MID,
	TTS_ADDR_COMPASS_END,
	TTS_ADDR_CONFIG,
	TTS_ADDR_DECREASE,
	TTS_ADDR_DEGREES_MID,
	TTS_ADDR_DEGREES_END,
	TTS_ADDR_DELTA_INTERVAL_MID,
	TTS_ADDR_DELTA_SIGNAL_MID,
	TTS_ADDR_DIGIT,
	TTS_ADDR_DISPLAY,
	TTS_ADDR_DTW_MID,
	TTS_ADDR_DTW_END,
	TTS_ADDR_ERROR,
	TTS_ADDR_EXT_MID,
	TTS_ADDR_FMT,
	TTS_ADDR_FMT_OPTS_MID,
	TTS_ADDR_FMT_OPTS_END,
	TTS_ADDR_FREQ,
	TTS_ADDR_GPS_MID,
	TTS_ADDR_GPS_END,
	TTS_ADDR_GPS_MOD,
	TTS_ADDR_GPS_OPTS_MID,
	TTS_ADDR_GPS_OPTS_END,
	TTS_ADDR_HDG_MID,
	TTS_ADDR_HDG_END,
	TTS_ADDR_HIGH_MID,
	TTS_ADDR_HIGH_END,
	TTS_ADDR_INCREASE,
	TTS_ADDR_INITIALIZING,
	TTS_ADDR_KNOTS_END,
	TTS_ADDR_LEFT,
	TTS_ADDR_LEVEL,
	TTS_ADDR_LOOP,
	TTS_ADDR_LOW_MID,
	TTS_ADDR_LOW_END,
	TTS_ADDR_MAGNETIC_MID,
	TTS_ADDR_MAGNETIC_END,
	TTS_ADDR_MAIN,
	TTS_ADDR_MAIN_MENU,
	TTS_ADDR_MAX_PERIOD_MID,
	TTS_ADDR_MEDIUM_MID,
	TTS_ADDR_MEDIUM_END,
	TTS_ADDR_MENU,
	TTS_ADDR_MESSAGE,
	TTS_ADDR_MINUS,
	TTS_ADDR_MIN_PERIOD_MID,
	TTS_ADDR_MODE,
	TTS_ADDR_MUTE,
	TTS_ADDR_MUTED,
	TTS_ADDR_NAUTICALMILES,
	TTS_ADDR_NAVIGATION,
	TTS_ADDR_NEARING,
	TTS_ADDR_NO_SIGNAL,
	TTS_ADDR_NONTARGETING,
	TTS_ADDR_NOTRCVING,
	TTS_ADDR_OFF_MID,
	TTS_ADDR_OFF_END,
	TTS_ADDR_ON_MID,
	TTS_ADDR_ON_END,
	TTS_ADDR_ONCOURSE,
	TTS_ADDR_OPTIONS,
	TTS_ADDR_PER_RPT_MID,
	TTS_ADDR_PER_RPT_END,
	TTS_ADDR_POINT,
	TTS_ADDR_PORT,
	TTS_ADDR_PORTA,
	TTS_ADDR_PORTA2B,
	TTS_ADDR_PORTB2A,
	TTS_ADDR_PORTB,
	TTS_ADDR_PRESENT,
	TTS_ADDR_RCVING,
	TTS_ADDR_READY,
	TTS_ADDR_REPORT,
	TTS_ADDR_RESOLUTION,
	TTS_ADDR_RIGHT,
	TTS_ADDR_SECONDS_MID,
	TTS_ADDR_SECONDS_END,
	TTS_ADDR_SELECTED,
	TTS_ADDR_SIGNAL,
	TTS_ADDR_SOURCE,
	TTS_ADDR_SPACE,
	TTS_ADDR_SPEECH,
	TTS_ADDR_SPEED_MID,
	TTS_ADDR_STATUS_BTN_OPTS_MID,
	TTS_ADDR_STATUS_BTN_OPTS_END,
	TTS_ADDR_STARBOARD,
	TTS_ADDR_ADJUST_MID,
	TTS_ADDR_SWITCH,
	TTS_ADDR_SWITCHING,
	TTS_ADDR_SWITCHING_OPTS_MID,
	TTS_ADDR_SWITCHING_OPTS_END,
	TTS_ADDR_SYSTEM,
	TTS_ADDR_SYSTEM_OPTS_MID,
	TTS_ADDR_SYSTEM_OPTS_END,
	TTS_ADDR_SYSTEM_RPT,
	TTS_ADDR_TARGET,
	TTS_ADDR_TARGETING,
	TTS_ADDR_TONE,
	TTS_ADDR_TRUE_MID,
	TTS_ADDR_TRUE_END,
	TTS_ADDR_TURNTO,
	TTS_ADDR_USE_MID,
	TTS_ADDR_USING,
	TTS_ADDR_VELOCITY,
	TTS_ADDR_VTW,
	TTS_ADDR_VERSION,
	TTS_ADDR_VOG_MID,
	TTS_ADDR_VOG_END,
	TTS_ADDR_VOLUME,
	TTS_ADDR_WPT_MID,
	TTS_ADDR_WPT_END,
	TTS_ADDR_WIND,
	TTS_ADDR_XTRACKERR,
	TTS_ADDR_A,
	TTS_ADDR_B,
	TTS_ADDR_C,
	TTS_ADDR_D,
	TTS_ADDR_E,
	TTS_ADDR_F,
	TTS_ADDR_G,
	TTS_ADDR_H,
	TTS_ADDR_I,
	TTS_ADDR_J,
	TTS_ADDR_K,
	TTS_ADDR_L,
	TTS_ADDR_M,
	TTS_ADDR_N,
	TTS_ADDR_O,
	TTS_ADDR_P,
	TTS_ADDR_Q,
	TTS_ADDR_R,
	TTS_ADDR_S,
	TTS_ADDR_T,
	TTS_ADDR_U,
	TTS_ADDR_V,
	TTS_ADDR_W,
	TTS_ADDR_X,
	TTS_ADDR_Y,
	TTS_ADDR_Z,
	TTS_ADDR_NOTE_C4,
	TTS_ADDR_NOTE_DF4,
	TTS_ADDR_NOTE_D4,
	TTS_ADDR_NOTE_EF4,
	TTS_ADDR_NOTE_E4,
	TTS_ADDR_NOTE_F4,
	TTS_ADDR_NOTE_GF4,
	TTS_ADDR_NOTE_G4,
	TTS_ADDR_NOTE_AF4,
	TTS_ADDR_NOTE_A4,
	TTS_ADDR_NOTE_BF4,
	TTS_ADDR_NOTE_B4,
	TTS_ADDR_NOTE_DBL_E4,
	TTS_ADDR_NOTE_E4_2,
	TTS_ADDR_NOTE_A4_B4,
	TTS_ADDR_NOTE_B4_A4,
	TTS_ADDR_NOTE_A4_F4,
	TTS_ADDR_NOTE_F4_A4,
	TTS_ADDR_NOTE_C4_E4,
	TTS_ADDR_NOTE_E4_C4,
	TTS_ADDR_NOTE_D4_F4,
	TTS_ADDR_NOTE_F4_D4,
	TTS_ADDR_NOTE_E4_G4,
	TTS_ADDR_NOTE_G4_E4,
	TTS_ADDR_NOTE_C5,
	TTS_ADDR_NOTE_DF5,
	TTS_ADDR_NOTE_D5,
	TTS_ADDR_NOTE_EF5,
	TTS_ADDR_NOTE_E5,
	TTS_ADDR_NOTE_GF5,
	TTS_ADDR_NOTE_G5,
	TTS_ADDR_TURN_TO_PORT,
	TTS_ADDR_TURN_TO_STBD,
	TTS_ADDR_HEADING_STEADY,
	TTS_ADDR_DELTA_STBD,
	TTS_ADDR_DELTA_PORT,
};
#else

extern int16 TtsAddrSpchTbl[TTS_ADDR_MAX_INDEX+1];

#endif


